name: Docker CI/CD for Strapi Backend

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*' # 也可以在打标签时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # 如果推送到 GHCR，这是必需的

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (性能优化)
        uses: docker/setup-buildx-action@v3

      - name: Docker Metadata (生成 tags 和 labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ccr.ccs.tencentyun.com/datalab/strapi # 替换为您的仓库地址
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern=v{{version}}

      - name: Login to Docker Hub/GHCR
        uses: docker/login-action@v3
        with:
          ## 假设使用 Docker Hub
          #username: ${{ secrets.DOCKER_USERNAME }}
          #password: ${{ secrets.DOCKER_PASSWORD }}
          # 或者使用 GHCR
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCLOUD_USERNAME}}
          password: ${{ secrets.TENFLOUD_PASSWORD}}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Dockerfile 所在的路径 (默认为仓库根目录)
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha # 开启缓存以加速后续构建
          cache-to: type=gha,mode=max
